### ISSUE TITLE
Is this PyPI package related?

### ISSUE THREAD

**Issue by franklinyu** [aragilar/virtualenv2#1]
There is [a package on PyPI with same name](https://pypi.org/project/virtualenv2/). Is that related to this project?

**Comment by aragilar** [comment]
Not as far as I know (I didn't upload it), my plan for this repo was to take ionelmc's work on the virtualenv-rewrite branch and include the newer changes from the main virtualenv repo (plus any relevant PRs), but I haven't had time.
